platform :ios, '15.0'

target 'Flash Chat iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flash Chat iOS13
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

end
